Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/EndOfLine:
  EnforcedStyle: lf

Style/HashSyntax:
  Enabled: false

Style/AndOr
  EnforcedStyle: conditionals