Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Style/HashSyntax:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals