version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=wrp
      - POSTGRES_DB=wetrockpolice_development
    ports:
      - '5432:5432'
    volumes:
      - wetrockpolice-postgres:/var/lib/postgresql/data:Z

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - wetrockpolice-redis:/var/lib/redis/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        RAILS_ENV: development
    # uncomment the following line to start a web server with a debugger
    # command: bundle exec rdebug-ide --debug --host 0.0.0.0 --port 1234 -- bin/rails server -p 3001 -b 0.0.0.0
    volumes:
      - .:/opt/wetrockpolice
      - /opt/wetrockpolice/tmp
      - /opt/wetrockpolice/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    
  webpacker:
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        RAILS_ENV: development
    command: bash -c "rm -rf /opt/wetrockpolice/public/packs && NODE_OPTIONS=--openssl-legacy-provider ./bin/webpack-dev-server"
    volumes:
      - .:/opt/wetrockpolice
      - /opt/wetrockpolice/tmp
      - /opt/wetrockpolice/node_modules
    ports:
      - '3035:3035'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - .:/opt/wetrockpolice
      - /opt/wetrockpolice/tmp
      - /opt/wetrockpolice/node_modules
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  wetrockpolice-redis:
  wetrockpolice-postgres: